- name: Directory is present
  file:
    path: "/composes/{{ project }}"
    state: directory

- name: Volume is present
  file:
    path: "{{ container_volume }}"
    mode: "{{ container_volume_mode }}"
    state: directory
  when: container_volume is defined

- name: Compose is present
  copy:
    src: "{{ project }}.yml"
    dest: "/composes/{{ project }}/docker-compose.yml"

- name: Containers are pulled
  command: docker-compose pull
  args:
    chdir: "/composes/{{ project }}"

- name: Containers are running
  command: docker-compose up -d
  args:
    chdir: "/composes/{{ project }}"
  when: not do_not_start_container is defined
