version: '2'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    ports:
      - 9200
      - 9300
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    restart: always

  logstash:
    container_name: logstash
    image: logstash
    ports:
      - 25826:25826
      - 25827:25827
    volumes:
      - /data/logstash/conf:/conf
    command: logstash -f /conf/syslog-collectd.conf
    restart: always

  kibana:
    container_name: kibana
    image: kibana
    ports:
      - 80:5601
    restart: always
