version: '2'

services:

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    restart: always
