version: '2'

services:

  registry:
    container_name: registry
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /data/registry:/var/lib/registry/docker/registry
    restart: always
